### ISSUE TITLE
broken on 1.1.4.28

### ISSUE THREAD

**Issue by muppeth** [CODeRUS/sailfishos-launcher-combined-patch#1]
tried re-applying the patch after updating OS but it fails. is it known issue or something went wrong with my phone?

**Comment by CODeRUS** [comment]
known, i have no time to update my patches for u13 now.

**Comment by muppeth** [comment]
np. was just wondering if only I'm affected since haven't seen anything on tjc. Thanks for the info and keep up the awesome work.

**Comment by heubergen** [comment]
Works now again, @muppeth could you please close the issue :)
