### ISSUE TITLE
App drawer background settings

### ISSUE THREAD

**Issue by ghost** [CODeRUS/sailfishos-launcher-combined-patch#3]
Not sure if it's a bug or a problem of mine, but when i restart the home or i reboot the phone, the  app drawer background becames transparent so i have to set it to my likes every time (i keep it with black background, as default).

**Comment by CODeRUS** [comment]
Fixed in commit https://github.com/CODeRUS/sailfishos-launcher-combined-patch/commit/1c7d91389c4bd630a349c1c8642515bf76b6b89a
